export const INITIAL_TAXONOMY = [
  {
    id: 1,
    name: 'Sports',
    slug: 'sports',
    icon: 'Trophy',
    description: 'Live scores, tournament highlights, athlete profiles, and upcoming matches across all sports.',
    subCategories: [
      { id: 101, name: 'Cricket', slug: 'cricket', description: 'IPL, Test matches, ODIs, and T20 updates.' },
      { id: 102, name: 'Volleyball', slug: 'volleyball', description: 'Beach volleyball, state leagues, and national tournaments.' },
      { id: 103, name: 'Football', slug: 'football', description: 'Champions League, Premier League, World Cup qualifiers.' },
      { id: 104, name: 'Basketball', slug: 'basketball', description: 'NBA highlights, EuroLeague, and college hoops.' },
      { id: 105, name: 'Tennis', slug: 'tennis', description: 'Grand Slams, ATP tour, and WTA rankings.' },
      { id: 106, name: 'Badminton', slug: 'badminton', description: 'BWF world tour, Thomas Cup, and singles action.' },
      { id: 107, name: 'Athletics', slug: 'athletics', description: 'Competition updates, records and athlete highlights.' },
      { id: 108, name: 'Formula 1', slug: 'formula-1', description: 'Race weekends, qualifying, results and driver updates.' },
      { id: 109, name: 'Motorsport', slug: 'motorsport', description: 'MotoGP, Le Mans, rally racing, and endurance championships.' }
    ]
  }
];

export const MOCK_TICKER_ITEMS = [
  { id: 1, tag: 'BREAKING', text: 'India Prepare for the Next Big Cricket Series: Squad, Schedule & Key Players Announced', category: 'Sports' },
  { id: 2, tag: 'F1 UPDATE', text: 'Race strategies finalized for upcoming Monaco Grand Prix weekend', category: 'Sports' },
  { id: 3, tag: 'FOOTBALL', text: 'Champions League draw sets up thrilling quarterfinals matchups', category: 'Sports' },
  { id: 4, tag: 'TENNIS', text: 'Grass court seedings updated ahead of Wimbledon championship open', category: 'Sports' }
];

export const MOCK_EVENTS = [
  {
    id: 201,
    title: 'National Grand Volleyball Championship 2026',
    slug: 'national-volleyball-championship-2026',
    description: 'The premier national volleyball event featuring top 16 state teams competing for the gold trophy with live commentary.',
    categoryName: 'Sports',
    subCategoryName: 'Volleyball',
    eventDate: '2026-09-15',
    eventTime: '09:00 AM PST',
    location: 'Pacific Sports Arena, San Francisco, CA',
    registrationUrl: '/blog/upcoming-volleyball-tournament-next-month',
    status: 'UPCOMING',
    organizer: 'National Volleyball Federation',
    coverImageUrl: 'https://images.unsplash.com/photo-1612872087720-bb876e2e67d1?auto=format&fit=crop&w=1200&q=80',
    createdAt: '2026-08-01T10:00:00Z'
  },
  {
    id: 203,
    title: 'Premier League Football Night: Derby Showdown',
    slug: 'premier-league-derby-showdown',
    description: 'High-stakes football showdown between top league rivals broadcasted live to millions of sports fans worldwide.',
    categoryName: 'Sports',
    subCategoryName: 'Football',
    eventDate: '2026-08-28',
    eventTime: '07:45 PM GMT',
    location: 'Wembley Stadium, London, UK',
    registrationUrl: '/blog/premier-league-derby-showdown-insights',
    status: 'UPCOMING',
    organizer: 'Premier League Committee',
    coverImageUrl: 'https://images.unsplash.com/photo-1508098682722-e99c43a406b2?auto=format&fit=crop&w=1200&q=80',
    createdAt: '2026-08-03T11:00:00Z'
  },
  {
    id: 205,
    title: 'Wimbledon Men\'s Singles Finals 2026',
    slug: 'wimbledon-singles-finals-2026',
    description: 'The final match of the historic grass tournament. Top-seeded rivals battle on Center Court.',
    categoryName: 'Sports',
    subCategoryName: 'Tennis',
    eventDate: '2026-07-12',
    eventTime: '02:00 PM BST',
    location: 'Center Court, London, UK',
    registrationUrl: '/blog/wimbledon-championship-finals-analysis',
    status: 'UPCOMING',
    organizer: 'All England Lawn Tennis Club',
    coverImageUrl: 'https://images.unsplash.com/photo-1595435934249-5df7ed86e1c0?auto=format&fit=crop&w=1200&q=80',
    createdAt: '2026-08-04T12:00:00Z'
  }
];

export const MOCK_BLOGS = [
  {
    id: 101,
    title: 'India Prepare for the Next Big Cricket Series: Squad, Schedule & Key Players',
    slug: 'india-prepare-next-big-cricket-series',
    summary: 'India names dynamic squad for the upcoming multi-format cricket series, focusing on spin-heavy bowling rotations.',
    content: `Cricket selectors have unveiled India's tactical squad lineup for the upcoming bilateral series. Key decisions include integrating young power hitters and maintaining strong spin depth for subcontinent pitches.`,
    coverImage: 'https://images.unsplash.com/photo-1540747913346-19e32dc3e97e?auto=format&fit=crop&w=1200&q=80',
    category: { id: 1, name: 'Sports', slug: 'sports' },
    subCategoryName: 'Cricket',
    tags: [{ id: 8, name: 'Cricket', slug: 'cricket' }, { id: 9, name: 'India Tour', slug: 'india-tour' }],
    author: {
      id: 6,
      name: 'Rahul Sharma',
      email: 'rahul@keryxsports.com',
      bio: 'Senior Cricket Editor & Tactician.',
      avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=300&q=80',
    },
    likesCount: 340,
    commentsCount: 45,
    readTime: '6 min read',
    status: 'PUBLISHED',
    isTrending: true,
    isFeatured: true,
    createdAt: '2026-08-10T10:15:00Z',
    isLiked: true,
    isBookmarked: true,
  },
  {
    id: 102,
    title: 'Upcoming Volleyball Tournament Next Month: Team Roster & Schedule Analysis',
    slug: 'upcoming-volleyball-tournament-next-month',
    summary: 'The national volleyball season reaches peak momentum as top teams prepare for next month’s tournament in San Francisco.',
    content: `Volleyball enthusiasts across the nation are gearing up for next month's Grand Volleyball Championship. With sixteen elite state teams competing, the tournament promises world-class spike setups, block defenses, and intense rally action.`,
    coverImage: 'https://images.unsplash.com/photo-1612872087720-bb876e2e67d1?auto=format&fit=crop&w=1200&q=80',
    category: { id: 1, name: 'Sports', slug: 'sports' },
    subCategoryName: 'Volleyball',
    tags: [{ id: 1, name: 'Volleyball', slug: 'volleyball' }, { id: 2, name: 'Tournament', slug: 'tournament' }],
    author: {
      id: 1,
      name: 'Marcus Vance',
      email: 'marcus@keryxsports.com',
      bio: 'Sports Analyst & Senior Editor.',
      avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=300&q=80',
    },
    likesCount: 215,
    commentsCount: 32,
    readTime: '5 min read',
    status: 'PUBLISHED',
    isTrending: true,
    isFeatured: false,
    createdAt: '2026-08-07T10:15:00Z',
    isLiked: false,
    isBookmarked: true,
  },
  {
    id: 103,
    title: 'Premier League Football Night: Derby Showdown Insights & Tactics',
    slug: 'premier-league-derby-showdown-insights',
    summary: 'A detailed tactical breakdown of the upcoming derby, highlighting expected team formations and wing attacks.',
    content: `High-stakes football showdown between top league rivals broadcasted live. Analysts predict high-pressing midfields and speed counters will decide the derby outcome.`,
    coverImage: 'https://images.unsplash.com/photo-1508098682722-e99c43a406b2?auto=format&fit=crop&w=1200&q=80',
    category: { id: 1, name: 'Sports', slug: 'sports' },
    subCategoryName: 'Football',
    tags: [{ id: 3, name: 'Football', slug: 'football' }, { id: 4, name: 'Premier League', slug: 'premier-league' }],
    author: {
      id: 5,
      name: 'David Carter',
      email: 'david@keryxsports.com',
      bio: 'Tactical Analyst specializing in European Football.',
      avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=300&q=80',
    },
    likesCount: 188,
    commentsCount: 20,
    readTime: '7 min read',
    status: 'PUBLISHED',
    isTrending: true,
    isFeatured: false,
    createdAt: '2026-08-08T11:00:00Z',
    isLiked: false,
    isBookmarked: false,
  },
  {
    id: 104,
    title: 'NBA Championship Contenders: Mid-Season Analytical Breakdown',
    slug: 'nba-championship-contenders-mid-season',
    summary: 'Examining key team statistics, defensive records, and MVP-contender form ahead of the All-Star break.',
    content: `With half the basketball season concluded, three dominant franchises stand out as true championship contenders, showing elite efficiency metrics.`,
    coverImage: 'https://images.unsplash.com/photo-1546519638-68e109498ffc?auto=format&fit=crop&w=1200&q=80',
    category: { id: 1, name: 'Sports', slug: 'sports' },
    subCategoryName: 'Basketball',
    tags: [{ id: 5, name: 'Basketball', slug: 'basketball' }, { id: 6, name: 'NBA', slug: 'nba' }],
    author: {
      id: 1,
      name: 'Marcus Vance',
      email: 'marcus@keryxsports.com',
      bio: 'Sports Analyst & Senior Editor.',
      avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=300&q=80',
    },
    likesCount: 154,
    commentsCount: 14,
    readTime: '6 min read',
    status: 'PUBLISHED',
    isTrending: true,
    isFeatured: false,
    createdAt: '2026-08-06T15:20:00Z',
    isLiked: false,
    isBookmarked: false,
  },
  {
    id: 105,
    title: 'Wimbledon Championship Finals Analysis: Key Player Rivalries',
    slug: 'wimbledon-championship-finals-analysis',
    summary: 'A look into historical head-to-head match records of the top two grass-court singles players.',
    content: `The grass court major reaches its pinnacle. Selectors and analysts weigh in on physical fitness, baseline service success, and mental durability.`,
    coverImage: 'https://images.unsplash.com/photo-1595435934249-5df7ed86e1c0?auto=format&fit=crop&w=1200&q=80',
    category: { id: 1, name: 'Sports', slug: 'sports' },
    subCategoryName: 'Tennis',
    tags: [{ id: 7, name: 'Tennis', slug: 'tennis' }, { id: 8, name: 'Wimbledon', slug: 'wimbledon' }],
    author: {
      id: 4,
      name: 'Sarah Jenkins',
      email: 'sarah@keryxsports.com',
      bio: 'Grand Slam Analyst & Tennis Historian.',
      avatarUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=300&q=80',
    },
    likesCount: 220,
    commentsCount: 28,
    readTime: '5 min read',
    status: 'PUBLISHED',
    isTrending: true,
    isFeatured: false,
    createdAt: '2026-08-09T09:00:00Z',
    isLiked: false,
    isBookmarked: false,
  },
  {
    id: 106,
    title: 'BWF World Tour: Badminton Rankings Shuffle & Contender Performance',
    slug: 'bwf-world-tour-badminton-rankings',
    summary: 'Analyzing the recent tour tournament results and their impact on the seedings for upcoming grand events.',
    content: `Fast rally badminton shifts power dynamics. Top Asian and European contenders showcase improved agility stats and backhand smashes.`,
    coverImage: 'https://images.unsplash.com/photo-1521537634199-673cb82ee2b2?auto=format&fit=crop&w=1200&q=80',
    category: { id: 1, name: 'Sports', slug: 'sports' },
    subCategoryName: 'Badminton',
    tags: [{ id: 10, name: 'Badminton', slug: 'badminton' }, { id: 11, name: 'BWF Tour', slug: 'bwf-tour' }],
    author: {
      id: 4,
      name: 'Sarah Jenkins',
      email: 'sarah@keryxsports.com',
      bio: 'Grand Slam Analyst & Tennis Historian.',
      avatarUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=300&q=80',
    },
    likesCount: 112,
    commentsCount: 9,
    readTime: '4 min read',
    status: 'PUBLISHED',
    isTrending: false,
    isFeatured: false,
    createdAt: '2026-08-04T10:00:00Z',
    isLiked: false,
    isBookmarked: false,
  },
  {
    id: 107,
    title: 'Athletics Speed Trials: High-Octane Record Breakers',
    slug: 'athletics-speed-trials-high-octane',
    summary: 'Highlights from the track and field championship trials, where three national sprint records were shattered.',
    content: `Runners delivered peak speeds under favorable wind conditions. Technology, training, and athletic stamina break double-decade records.`,
    coverImage: 'https://images.unsplash.com/photo-1476480862126-209bfaa8edc8?auto=format&fit=crop&w=1200&q=80',
    category: { id: 1, name: 'Sports', slug: 'sports' },
    subCategoryName: 'Athletics',
    tags: [{ id: 12, name: 'Athletics', slug: 'athletics' }, { id: 13, name: 'Track & Field', slug: 'track-and-field' }],
    author: {
      id: 7,
      name: 'Dr. Elena Rostova',
      email: 'elena@keryxsports.com',
      bio: 'Sports Science Specialist and Author.',
      avatarUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=300&q=80',
    },
    likesCount: 165,
    commentsCount: 15,
    readTime: '5 min read',
    status: 'PUBLISHED',
    isTrending: false,
    isFeatured: false,
    createdAt: '2026-08-03T11:00:00Z',
    isLiked: false,
    isBookmarked: false,
  },
  {
    id: 108,
    title: 'Formula 1 Monaco GP: Driver Strategy & Qualifying Session Highlights',
    slug: 'formula-1-monaco-gp-driver-strategy',
    summary: 'A breakdown of street-circuit tire selections, aerodynamics, and driver qualifications.',
    content: `Monaco streets demand extreme mechanical grip. We evaluate the pit stop strategy and overtake options of leading constructors drivers.`,
    coverImage: 'https://images.unsplash.com/photo-1568605117036-5fe5e7bab0b7?auto=format&fit=crop&w=1200&q=80',
    category: { id: 1, name: 'Sports', slug: 'sports' },
    subCategoryName: 'Formula 1',
    tags: [{ id: 14, name: 'Formula 1', slug: 'f1' }, { id: 15, name: 'Grand Prix', slug: 'grand-prix' }],
    author: {
      id: 1,
      name: 'Alex Rivera',
      email: 'alex@keryxsports.com',
      bio: 'Motorsports Commentator & Racing Specialist.',
      avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=300&q=80',
    },
    likesCount: 295,
    commentsCount: 41,
    readTime: '6 min read',
    status: 'PUBLISHED',
    isTrending: false,
    isFeatured: false,
    createdAt: '2026-08-05T14:30:00Z',
    isLiked: false,
    isBookmarked: false,
  },
  {
    id: 109,
    title: 'MotoGP Season Opener: Motorsport Endurance & Technical Spec Evolution',
    slug: 'motogp-season-opener-motorsport-endurance',
    summary: 'Reviewing the team upgrades, engine adjustments, and cornering stability modifications in new bikes.',
    content: `Two-wheel engineering pushes limits at the season opener. Ride height devices and aero bodies spark debates among paddock engineers.`,
    coverImage: 'https://images.unsplash.com/photo-1558981806-ec527fa84c39?auto=format&fit=crop&w=1200&q=80',
    category: { id: 1, name: 'Sports', slug: 'sports' },
    subCategoryName: 'Motorsport',
    tags: [{ id: 16, name: 'MotoGP', slug: 'motogp' }, { id: 17, name: 'Motorsport', slug: 'motorsport' }],
    author: {
      id: 1,
      name: 'Alex Rivera',
      email: 'alex@keryxsports.com',
      bio: 'Motorsports Commentator & Racing Specialist.',
      avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=300&q=80',
    },
    likesCount: 140,
    commentsCount: 12,
    readTime: '5 min read',
    status: 'PUBLISHED',
    isTrending: false,
    isFeatured: false,
    createdAt: '2026-08-02T10:15:00Z',
    isLiked: false,
    isBookmarked: false,
  }
];

export const MOCK_COMMENTS = [
  {
    id: 1,
    content: "Outstanding analysis on the upcoming volleyball championship roster! Looking forward to seeing the defensive spikes.",
    authorName: "Marcus Vance",
    authorAvatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=150&q=80",
    createdAt: "2026-08-07T12:00:00Z"
  },
  {
    id: 2,
    content: "The bowling strategy outline for the next test match is spot on. Team India needs solid spin tactics in the middle overs.",
    authorName: "Rahul Sharma",
    authorAvatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=150&q=80",
    createdAt: "2026-08-08T14:15:00Z"
  }
];

export const MOCK_NEWS = [
  {
    id: 301,
    title: 'BREAKING: National Volleyball Championship Finals Scheduled for Next Month in San Francisco',
    slug: 'national-volleyball-championship-finals-scheduled-next-month',
    summary: 'The National Volleyball Federation confirms California venue for next month’s tournament featuring top 16 state teams.',
    content: `San Francisco will host next month’s highly anticipated National Volleyball Championship Finals at the Pacific Sports Arena. Sixteen elite teams across the nation will compete for the gold trophy with live TV broadcast coverage.`,
    categoryName: 'Sports',
    subCategoryName: 'Volleyball',
    imageUrl: 'https://images.unsplash.com/photo-1612872087720-bb876e2e67d1?auto=format&fit=crop&w=1200&q=80',
    isBreaking: true,
    isTrending: true,
    isTopStory: true,
    authorName: 'Marcus Vance',
    viewsCount: 4120,
    publishedAt: '2026-08-08T18:30:00Z'
  },
  {
    id: 302,
    title: 'F1 Monaco Grand Prix: Ferrari and Red Bull Battle for Pole Position',
    slug: 'f1-monaco-gp-pole-position-battle',
    summary: 'Qualifying wraps up with a tight margin between the top three constructors drivers.',
    content: `Monaco streets witnessed extreme high-downforce action as drivers pushed limits during the final practice and qualifying sessions.`,
    categoryName: 'Sports',
    subCategoryName: 'Formula 1',
    imageUrl: 'https://images.unsplash.com/photo-1568605117036-5fe5e7bab0b7?auto=format&fit=crop&w=1200&q=80',
    isBreaking: false,
    isTrending: true,
    isTopStory: true,
    authorName: 'Alex Rivera',
    viewsCount: 3280,
    publishedAt: '2026-08-08T14:15:00Z'
  },
  {
    id: 303,
    title: 'Tennis Rankings Update: Defending Champions Maintain Lead Post Wimbledon Warmups',
    slug: 'tennis-rankings-update-wimbledon-warmups',
    summary: 'ATP and WTA update seedings ahead of next week’s major grass tournament.',
    content: `The grass court preparations have concluded with notable shifts in the top 10 rankings. Defending champions remain comfortably ahead.`,
    categoryName: 'Sports',
    subCategoryName: 'Tennis',
    imageUrl: 'https://images.unsplash.com/photo-1595435934249-5df7ed86e1c0?auto=format&fit=crop&w=1200&q=80',
    isBreaking: false,
    isTrending: false,
    isTopStory: true,
    authorName: 'Sarah Jenkins',
    viewsCount: 1950,
    publishedAt: '2026-08-07T09:45:00Z'
  }
];
